### ISSUE TITLE
Color Wheel Not Displaying

### ISSUE THREAD

**Issue by dac21** [ljmerza/light-entity-card#30]
I have lights that support the color wheel (on the Smart Life App) but the color wheel does not appear in this card.  Thoughts?

![image](https://user-images.githubusercontent.com/35934973/75102650-13f19200-55bd-11ea-9b53-8adc14fece68.png)

**Comment by ljmerza** [comment]
Hello, sorry, I did see this but have been busy with my real projects. HA uses a supported_features attribute with is a number that represents bits. If you look [here](https://github.com/home-assistant/home-assistant-polymer/blob/7e584402ea18699478553b8cba393fed8698a004/src/data/light.ts) you'll see what bits represent a feature. In this case `color` (the color wheel) is 16. For the entity that does not show the color wheel, find the `supported_features` attribute. If you do bit wise and entity_attr `16 & entity_attr_value` and it equals `1` then that means the entity supports color wheel. If `0` then it does not. I would assume HA is reporting you entity does not support color wheel and that's why the wheel is not showing up.

Send me a picture of the full state/attributes of the entity in question and I can check the bits myself

**Comment by dac21** [comment]
So the light shows supported feature of 1.  But see the picture in the app.  How do I get the supported features updated.



Dennis Conrad

**Comment by ljmerza** [comment]
There's nothing I can do then. HA is reporting the only feature this entity has is to turn on and off. If you believe it should be able to do more than that, then you'll need to open a ticket with HA. This card can't force HA to do something it says can't be done. If support is added in HA, then this card should work automatically.

**Comment by dac21** [comment]
Thanks
