### ISSUE TITLE
Very sad to hear that you've stopped the development, it was a key part for the setup

### ISSUE THREAD

**Issue by fribse** [ljmerza/light-entity-card#48]
Hi there

Thankyou for all the hard work on this over the years, it saddens me that you've given up on the development of the card, it was my go-to light card :-)
I hope the HA developers will either pick up your card, or make it feasable for you to continue at some point.

**Comment by ljmerza** [comment]
I've looked into this more today and there's no way to load the custom elements I need from the custom card itself. To further explain, as of HA 0.115, you can't use the built in elements such as dropdown, checkbox, and color-picker from a custom card - you have to create your own now. To get this card working again I would need to:

- create checkbox, dropdown, and color-picker components
- edit the CSS of these three to match HA's theme

This would introduce a ton of bloat to the card and I'd have to keep up with changes in HA UI to match UI of custom elements in the future. This is also a ton of extra work. You can't simply import paper elements into the card because these are already imported so importing them again throws errors. You have to build from scratch.

I've asked some devs about this and it's low priority to get these element working again for custom card developers. I suggest opening an issue on frontend Home Assistant. Maybe if enough people complain they will care.

https://github.com/home-assistant/frontend

**Comment by iantrich** [comment]
@ljmerza I'm actually pushing for custom card support to be a top priority for Hacktoberfest. Would appreciate your involvement in the discussions and proposals

**Comment by ljmerza** [comment]
I hope something does come out of it this time. Custom cards has been pushed to the side for too long.

**Comment by iantrich** [comment]
Yeah, I think frontend should rollback the lazy more-info loading until a reliable working solution is in place to not break custom cards the relied on these elements.

cc @ludeeus @bramkragten

**Comment by fribse** [comment]
HA in it's core is not prettified enough, it's an engine, and does the basics, a lot of my lovelace interface relies on custom cards, as they make something look familiar for the family, a lot of my interface is going down the drain without custom cards, which is also why I regularly send 'coffee' or 'beer' to developers of these (with my limited budget I select one/month :-) ).
I'm 'only' a user, but point me in the right direction, and I'll get into it with Frenck :-D

**Comment by fribse** [comment]
I updated my post in the forums: https://community.home-assistant.io/t/custom-light-card-gone-with-0-115x-what-are-you-using-now/228793/2

**Comment by ljmerza** [comment]
devs have reverted code that broken this card in 0.115.3
